version: '3.8'

networks:
  trino_network:
    driver: bridge

volumes:
  mysql-data:
  pg-data:

services:
  # =======================================================
  # MySQL (ventas_db)
  # =======================================================
  mysql:
    image: mysql:8.0
    container_name: mysql
    hostname: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: demo
      MYSQL_PASSWORD: demo123
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      # scripts de inicialización
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - trino_network

  # =======================================================
  # PostgreSQL (productos_db)
  # =======================================================
  postgres:
    image: postgres:15
    container_name: postgres
    hostname: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo123
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
      # scripts de inicialización
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - trino_network

  # =======================================================
  # Trino
  # =======================================================
  trino:
    image: trinodb/trino:472
    container_name: trino
    hostname: trino
    restart: unless-stopped
    user: root
    environment:
      - TRINO_CONFIG_DIR=/etc/trino
    volumes:
      - ./trino/conf:/etc/trino
      - ./trino/conf/catalog:/etc/trino/catalog
    depends_on:
      - mysql
      - postgres
    ports:
      - "8080:8080"
    networks:
      - trino_network
